### ISSUE TITLE
Замечания по 1 лабе

### ISSUE THREAD

**Issue by veresnikov** [In1or/dop-web#1]
1. issue лучше не стоит удалять, не очень понятно какие замечания исправлены, лучше отписать что исправлено в коментарий
2. Все поля у Survey строки, и все могут быть null. Стоит определить какие типы данных нужно проставить полям, например age это скорее число. Почему email может быть null?
3. В именовании приватных функций не нужен _
4. loadFromFile не совсем понятно, зачем функция принимает в себя Survey, она же его загружает из файла
5. Переносы строки с помощью br это скорее костыль, стоит поискать более лаконичное решение
6. SurveyFileStorage сейчас имеет намертво зашитый путь к директории с данными, стоит вынести его в констурктор, что бы была возможность в случае необходимости подменить его
7. Приватные функции располагают после публичных

**Comment by In1or** [comment]
0b72be16dc8d3f9cdc22614ca908969486a2bfda - Тут я исправил основные замечания
6ac29c25504ecc94570be833c58a540cd37b68b5 - А тут заменил "< /br >" на PHP_EOL

**Comment by veresnikov** [comment]
Осталось парочка замечаний
1) Обязательные параметры лучше передавать в функции первыми
2) Функция saveToFile сейчас смущает. Предложение, сейчас функция для случая когда файл существует делает и когда файла нет имеет разную логику, в целом похожую. Для случая когда файл существует можно попробовать переиспользовать loadFromFile, т.е загрузить Survey, изменить данные, сохранить как обычно

**Comment by In1or** [comment]
ca63c0b313a5e7762449888ad002b4c2d393c8e1 - Как ты и предложил я переиспользовал loadFromFile
 Из-за неаккуратного пуша прошлые коммиты пропали(

**Comment by veresnikov** [comment]
микро замечание https://github.com/In1or/dop-web/commit/ca63c0b313a5e7762449888ad002b4c2d393c8e1#r72918323

**Comment by In1or** [comment]
Это надо было для обработки ошибки
Вернуть обратно?

**Comment by veresnikov** [comment]
поле email обязательное, странно что класс допускает возможность его отсутствие

**Comment by In1or** [comment]
https://github.com/In1or/dop-web/commit/6e410e3c699dca0a44fd80b0071c86cd43c72f16#r73101979 - Исправил
